# Generated by Django 6.0.7 on 2026-08-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='raw_moisture',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
