# Generated by Django 6.0.7 on 2026-08-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_sensorreading_raw_moisture'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['plant_id', '-recorded_at'], name='plant_recorded_idx'),
        ),
    ]
